### ISSUE TITLE
mejoras 

### ISSUE THREAD

**Issue by ideazconsultores1** [MisaelUrq/Blueberry-Issues#1]
buen dia, trabajando con la aplicacion surgio lo siguiente:
1. reasignar agente en los tikets, ya que se asigna a un agente, y puede que al final otro agente realice el servicio.
2. vista de tikets: en la vista de los tikets necesitamos que venga mas informacion: agente, empresa y nivel de urgencia. ( tambien poner al momento de dar de alta un tiket, un boton para poner el nivel de prioridad o urgencia, alta, media, baja o 1,2,3)
3. que se puedan iniciar 2 tikets al mismo tiempo ya que la mayoria de veces los agentes, trabajan en 2 o mas servicios al mismo tiempo.
4. cuando se pone pause a una llamada, se tiene que cerrar la aplicacion para abrirlo de nuevo.

**Comment by MisaelUrq** [comment]
Gracias por reportar los errores, como son varios puntos cada uno lo converti en un problema por  separado, por favor hagan esto en las siguientes, ya que será más facil para ver que eh terminado y que no. 

Por ahora cerraré esto, para poder dejar los problemas individuales y de todos esos el 4 parece ser el único error como tal, mientras que los demás son mejoras, por lo tanto el 4 tomara prioridad.
