### ISSUE TITLE
Comentarios

### ISSUE THREAD

**Issue by ideazconsultores1** [MisaelUrq/Blueberry-Issues#2]
Hola Misael.
Te paso mi cartita al Niño Dios.
Desde el día de ayer el sistema comenzó a fallar, de hecho hoy no he podido trabajar en el por que al momento de dar clic en cualquiera de las opciones de lado izquierdo, el sistema se cierra.
Cuando trabaje en el encontré varias situaciones:
1. No te permite trabajar en mas de un ticket a la vez, algo que es muy común con nosotros.
2. El listado de las empresas se muestra conforme las vamos capturando lo que al momento de realizar la búsqueda para crear un ticket es algo entretenido.
3. No nos permite modificar información de la empresa una vez guardada, como lo es RFC y Domicilio.
4. No podemos validar a quien esta asignado el ticket, y por lo tanto, no lo podemos reasignar al momento de tomarlo.
5. Necesitamos que en la pantalla de Tickets este dividido en columnas, una para Agente, Empresa, Prioridad; en la que 1 sea Urgente, 2 Moderado, 3 Normal
6. En el equipo de Kike no funciona =(

Por el momento son las que me acuerdo, si tengo otra te la hago llegar, mil gracias

**Comment by MisaelUrq** [comment]
Gracias  por reportar los errores, unos eran repetidos de una lista anterior, y como mencione ahí, para mi sería mejor si pueden reportar cada problema por individual, ya que hace el seguimiento más facil para mi.  

Por el momento, podrían ir los problemas que son de fallas del sistema y podrían describir que es lo que hicieron antes de que la falla ocurriera, en caso de que se halla  presentado así desde el inicio  pues lo veriamos entonces el viernes que vaya.

Y pues por ahora cerraré esto para enfocarnos en los problemas por individual.
